name: Haraj Real Estate Scraper

on:
  workflow_dispatch:          # تشغيل يدوي

jobs:
  scrape-real-estate:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install pandas requests beautifulsoup4 pillow openpyxl boto3 python-dotenv

      - name: Run scraper
        env:
          CF_R2_ACCESS_KEY_ID: ${{ secrets.CF_R2_ACCESS_KEY_ID }}
          CF_R2_SECRET_ACCESS_KEY: ${{ secrets.CF_R2_SECRET_ACCESS_KEY }}
          CF_R2_ENDPOINT_URL: ${{ secrets.CF_R2_ENDPOINT_URL }}
          CF_R2_BUCKET_NAME: ${{ secrets.CF_R2_BUCKET_NAME }}
        run: python haraj_pipeline.py --cat-name Real_Estate

      - name: Upload stats
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: request-stats
          path: request_stats_Real_Estate.json